version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - dogsled
    - durationcheck
    - errorlint
    - exhaustive
    - forbidigo
    - gochecknoinits
    - goconst
    - godot
    - gomodguard
    - goprintffuncname
    - ineffassign
    - makezero
    - nakedret
    - nlreturn
    - nolintlint
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unused
    - whitespace
    - wsl
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
    errorlint:
      errorf: true
    exhaustive:
      default-signifies-exhaustive: false
    funlen:
      lines: 100
      statements: 45
    gocognit:
      min-complexity: 15
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - dupImport
        - unnecessaryBlock
        - hugeParam
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 10
    misspell:
      locale: US
    nestif:
      min-complexity: 4
    nolintlint:
      require-explanation: true
      require-specific: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - godot
          - paralleltest
        path: integration-test
      - linters:
          - godot
        path: internal/controller/http
      - linters:
          - err113
          - funlen
        path: (.+)_test.go
    paths:
      - docs
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/device-management-toolkit/go-wsman-messages/v2)
        - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
        - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
        - alias # Alias section: contains all alias imports. This section is not present unless explicitly enabled.
        - localmodule # Local module section: contains all local packages. This section is not present unless explicitly enabled.
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - docs
      - third_party$
      - builtin$
      - examples$
